project:
  type: website

website:
  title: "rauwendaal.net"
  site-url: "https://raegnar.github.io/rauwendaal.net/"
  navbar:
    right:
      # - about.qmd
      # - blog.qmd
      # - resume.rmd
      - publications.qmd
      - icon: github
        href: https://github.com/raegnar
      - icon: twitter
        href: https://twitter.com/raegnar
      - icon: linkedin
        href: https://linkedin.com/in/randall-rauwendaal-6ba01a7/
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css
# execute:
#   freeze: auto



