project:
  type: website

website:
  title: "rauwendaal.net"
  site-url: "https://rauwendaal.net"
  navbar:
    right:
      - about.qmd
      # - blog.qmd
      # - resume.rmd
      - publications.qmd
      - icon: github
        href: https://github.com/raegnar
      - icon: twitter
        href: https://twitter.com/raegnar
format:
  html:
    theme: litera
    css: styles.css
# execute:
#   freeze: auto



